namespace Negociacoes.WebApi.Enumeradores
{
    public enum TipoNegociacaoComposicaoCarga
    {
        COMPOSICAO_CARGA_CRIADA = 1,
        COMPOSICAO_CARGA_ENVIADA_FORNECEDOR = 2,
        COMPOSICAO_CARGA_EM_NEGOCIACAO = 3,
        COMPOSICAO_CARGA_EM_NEGOCIACAO_EMERGENCIAL = 4,
        COMPOSICAO_CARGA_ACEITA = 5,
        COMPOSICAO_CARGA_EM_NEGOCIACAO_ACEITA = 6,
        COMPOSICAO_CARGA_EM_NEGOCIACAO_EMERGENCIAL_ACEITA = 7,
        COMPOSICAO_CARGA_CANCELADA = 8
    }
}
